### ISSUE TITLE
PHP 8.3 issues?

### ISSUE THREAD

**Issue by iMattPro** [s9e/SweetDOM#1]
What do you make of this (saw this while running unit tests with PHP 8.3 for a phpBB extension)

PHP Fatal error:  Declaration of s9e\SweetDOM\Element::insertAdjacentElement(string $where, s9e\SweetDOM\Element $element): s9e\SweetDOM\Element must be compatible with DOMElement::insertAdjacentElement(string $where, DOMElement $element): ?DOMElement in /home/runner/work/phpBB/vendor/s9e/sweetdom/src/Element.php on line 141

**Comment by JoshyPHP** [comment]
I don't have PHP 8.3 in my Linux distribution's repository so that's the first time I hear about it. I'm surprised that API is being implemented in PHP because [it's marked as "legacy" in DOM](https://dom.spec.whatwg.org/#ref-for-dom-element-insertadjacentelement) but in retrospect I realize I should have played it safe and maybe rename the userland implementation to avoid conflicts.

At the moment I don't see any other way than just change the return types of `insertAdjacentElement` and `insertAdjacentText` to match their PHP 8.3 implementation. Obviously it breaks backward compatibility but I don't think there's an alternative here. Luckily I don't think too many people use those specific methods.

**Comment by JoshyPHP** [comment]
Oh, I've just realized that past me was much more considerate of future me than I thought and that `insertAdjacentText` is fine. I thought it returned a `DOMNode` for some reason but the signature should be alright. So it's really only `insertAdjacentElement`'s return type that needs to be changed from `self` to `DOMElement`. Come to think of it, it would be nice if PHP's implementation was typed against `static` because it would probably solve it without messing up with IDEs and static code analysers.

**Comment by JoshyPHP** [comment]
In the end, I only had to change `insertAdjacentElement`'s argument type from `s9e\SweetDOM\Element` to `DOMElement`. PHP is fine with its return type so I don't foresee any further complications there but please let me know if you observe any issue. I intend to publish a release within the next few days.

Moving forward I intend to remove the userland implementations from the class. A polyfill can be implemented via magic methods so that PHP >= 8.3 always uses the native implementation.

**Comment by iMattPro** [comment]
This resolved the issue. Thanks!
