### ISSUE TITLE
Document::query return type

### ISSUE THREAD

**Issue by SychO9** [s9e/SweetDOM#3]
There seems to be an issue with what's returned by `Document::query`, I can't really tell what's exactly causing this.

https://discuss.flarum.org/d/33746-an-error-occurred-while-trying-to-load-this-page/13

**Comment by JoshyPHP** [comment]
What version of PHP is that? Judging by the stack trace, it might be an issue in ext/dom.

**Comment by SychO9** [comment]
it's 8.1.2 so it might be the same as this in that case: https://github.com/s9e/TextFormatter/issues/226

**Comment by JoshyPHP** [comment]
Coincidentally, I'm currently evaluating using some userland workarounds for the most common ext/dom bugs. You can try it out locally with this:

```
composer require s9e/sweetdom:dev-Workarounds
```

The branch is temporary and it may stop working and/or disappear at any time but if it fixes that particular issue, that'll be valuable information.

**Comment by JoshyPHP** [comment]
[I have updated the library](https://github.com/s9e/SweetDOM/commit/8a97397b1e1beca1b1bb389630ce79c6aca1e16d) to throw a `RuntimeException` with a meaningful message if a query returned `false` rather than a `DOMNodeList`. That will guarantee that the return type is always correct.

[According to the PHP manual](https://www.php.net/manual/en/domxpath.query.php#refsect1-domxpath.query-returnvalues), there are two reasons for `DOMXPath::query` to return `false`: either the expression is malformed, or the context node is invalid. We know that the expression is correct, so it has to be an issue with the node. I don't know what makes a node "invalid". For instance, a disconnected node (with no parent) is a valid context node. A node from a different document is not valid, but it generates a PHP error rather than cause the query to return `false`. My best guess is that it's simply an `ext/dom` bug that causes the node to be invalid and most likely, that's a bug that's already been fixed.

I'm closing this issue as there isn't anything more to do, but feel free to reopen is you find a way to reproduce it on a recent version of PHP.
